name: Hourly Main Runner

on:
  schedule:
    # 每小時執行一次 (在每小時的第 0 分)
    - cron: '0 * * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  run-main-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 您可以指定所需的 Python 版本

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
        shell: bash

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth-oauthlib google-auth-httplib2 requests Pillow pytesseract
        shell: bash

      - name: Create Google Credentials File
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: echo "$GOOGLE_CREDENTIALS_JSON" > nine-sols-754f9adc71aa.json
        shell: bash

      - name: Run main.py
        run: python main.py
        shell: bash
