name: Sync Country Stats

on:
  schedule:
    # 每 30 分鐘執行一次
    - cron: '*/30 * * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  run-main-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 您可以指定所需的 Python 版本

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth-oauthlib google-auth-httplib2 requests Pillow easyocr numpy discord.py python-dotenv
        shell: bash

      - name: Create Google Credentials File
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: echo "$GOOGLE_CREDENTIALS_JSON" > nine-sols-754f9adc71aa.json
        shell: bash

      - name: Run selfBotExecutor.py # 新增執行 self bot 的步驟
        env:
          DISCORD_USER_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }} # 將 Secret 注入環境變數
        run: python selfBotExecutor.py
        shell: bash

      - name: Run main.py
        run: python main.py
        shell: bash

